### ISSUE TITLE
500 server error when paying with MetaMask and DAI

### ISSUE THREAD

**Issue by ligi** [Web3Modal/web3modal-checkout#3]
for this URL: https://checkout.web3modal.com/?currency=DAI&amount=0.95&to=0x68a0921f7abf88404b4573fc2f15335ea75646b3

we get this:

![Selection_044](https://user-images.githubusercontent.com/111600/111631368-99ad3480-87f3-11eb-94f0-d233c7e49911.png)

it tries to load:

`ethereum-api.xyz/token-balance?address=0x0402c3407dcBD476C3d2Bbd80d1b375144bAF4a2&contractAddress=0x6b175474e89094c44da98b954eedeac495271d0f&chainId=1:1 `

Failed to load resource: the server responded with a status of 500 ()

**Comment by ligi** [comment]
Token-balance should be available via normal ethereum RPC right - so maybe not use ethereum-api.xyz here?

**Comment by pedrouid** [comment]
yeah in the past I've used ethereum-api.xyz as way to aggregate all my rpc requests and also Blockscout requests but Blockscout dropped support for most chains now and it makes more sense to just use RPC endpoints directly

**Comment by ligi** [comment]
@pedrouid thanks for the reply! Can you provide a timing for the fix so we can align it with our internal testing?

**Comment by pedrouid** [comment]
I've created a PR called refactor (#4) that removes that API completely including replacing web3.js with ethers.js. However I didn't test it so I would look for a JS dev to go through it, test and fix if necessary

**Comment by pedrouid** [comment]
I've merged the changes with the PR #4 after @wslyvh reviewed them

**Comment by ligi** [comment]
is it also deployed? I still see this error:

![image](https://user-images.githubusercontent.com/111600/114381370-555f4b00-9b8b-11eb-9fd6-0c22d08ecee0.png)

**Comment by pedrouid** [comment]
My bad... I've realized I had to merge to production branch also. Just tested it and it works 👌
